//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MathLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal number of operands.
        /// </summary>
        internal static string ArgumentExceptionMsg {
            get {
                return ResourceManager.GetString("ArgumentExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.01745329251994329576923690768489.
        /// </summary>
        internal static string DegreeConverterConst {
            get {
                return ResourceManager.GetString("DegreeConverterConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator should not be 0 in division.
        /// </summary>
        internal static string DivideByZeroExceptionMsg {
            get {
                return ResourceManager.GetString("DivideByZeroExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid base.
        /// </summary>
        internal static string ExponentExceptionMsg {
            get {
                return ResourceManager.GetString("ExponentExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression evaluation failed, Try checking the input format.
        /// </summary>
        internal static string ExpressionEvaluationFailedMsg {
            get {
                return ResourceManager.GetString("ExpressionEvaluationFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operation should have two operands and one operator.
        /// </summary>
        internal static string InvalidBinaryOperation {
            get {
                return ResourceManager.GetString("InvalidBinaryOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class full name is invalid for the operator.
        /// </summary>
        internal static string InvalidClassFullNameExceptionMsg {
            get {
                return ResourceManager.GetString("InvalidClassFullNameExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expression.
        /// </summary>
        internal static string InvalidExpressionExceptionMsg {
            get {
                return ResourceManager.GetString("InvalidExpressionExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is not valid, it should follow all required rules.
        /// </summary>
        internal static string InvalidExpressionFormat {
            get {
                return ResourceManager.GetString("InvalidExpressionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument in log or ln should not be zero.
        /// </summary>
        internal static string InvalidLogException {
            get {
                return ResourceManager.GetString("InvalidLogException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand is not valid, it should be a valid double.
        /// </summary>
        internal static string InvalidOperandMsg {
            get {
                return ResourceManager.GetString("InvalidOperandMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either operator or operand are not in correct position.
        /// </summary>
        internal static string InvalidPositionExceptionMsg {
            get {
                return ResourceManager.GetString("InvalidPositionExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operation should have one operand and one operator.
        /// </summary>
        internal static string InvalidUnaryOperation {
            get {
                return ResourceManager.GetString("InvalidUnaryOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result is very large to store..
        /// </summary>
        internal static string OutOfRangeExceptionMsg {
            get {
                return ResourceManager.GetString("OutOfRangeExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square root of negative number is not possible.
        /// </summary>
        internal static string RootOfNegativeExceptionMsg {
            get {
                return ResourceManager.GetString("RootOfNegativeExceptionMsg", resourceCulture);
            }
        }
    }
}
